version: "3.8"
name: "examon"

networks:
  examon_net:
    driver: bridge    
    driver_opts:
      com.docker.network.driver.mtu: 1450

services:
  examon:
    build:
      context: .
    image: examonhpc/examon:0.2.1
    volumes:  
      - type: bind
        source: ./lib/examon-common
        target: /etc/examon_deploy/examon/lib/examon-common
      - type: bind
        source: ./web/examon-server
        target: /etc/examon_deploy/examon/web/examon-server
      - type: bind
        source: ./publishers/examon_pub
        target: /etc/examon_deploy/examon/publishers/examon_pub
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"
    restart: always
    ports:
      - "1883:1883"
      - "5000:5000"
    networks:
      - examon_net
    environment:
      - EX_KAIROSDB_HOST=kairosdb
    depends_on:
      - kairosdb

  grafana:
    build:
      context: ./docker/grafana
    image: examonhpc/grafana:7.3.10 
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana_volume:/var/lib/grafana
    networks:
      - examon_net
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=Password
      - GF_INSTALL_PLUGINS=ae3e-plotly-panel 0.4.0,grafana-piechart-panel,yesoreyeram-infinity-datasource 0.8.8,marcusolsson-gantt-panel 0.7.5,flant-statusmap-panel 0.5.1,gapit-htmlgraphics-panel 1.3.3
    depends_on:
      - kairosdb

  kairosdb:
    build:
      context: ./docker/kairosdb
    image: examonhpc/kairosdb:1.2.2
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"
    restart: always
    ports:
      - "8083:8083"    
    networks:
      - examon_net
    environment:      
      - CASSANDRA_HOST_LIST=cassandra:9042
    depends_on:
      - cassandra

  cassandra:
    build:
      context: ./docker/cassandra
    image: examonhpc/cassandra:3.0.19
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"
    restart: always
    ports:
      - "9042:9042"
    volumes:
      - cassandra_volume:/var/lib/cassandra
    networks:
      - examon_net
    environment:
      - CASSANDRA_CLUSTER_NAME=examon
      - CASSANDRA_BROADCAST_ADDRESS=cassandra
      - CASSANDRA_START_RPC=true
      - CASSANDRA_LISTEN_ADDRESS=auto

volumes:
  cassandra_volume:
  grafana_volume:
  
